name: Vote app deploy
run-name: ${{ github.actor }} is deploying the Voting app 🚀

on:
  push:
    branches:
      - '**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: gcp auth
        uses: 'google-github-actions/auth@v2' 
        id: auth
        with:
          project_id: 'cc-spring2025' # update with your project ID
          workload_identity_provider: '' # update with your Workload Identity Pool
